local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn'kahet: The Old Kingdom"] = {3, 1, "Ahn'kahet: The Old Kingdom"}
c["Assault on Violet Hold"] = {7, 1, "Assault on Violet Hold"}
c["Auchenai Crypts"] = {2, 1, "Auchenai Crypts"}
c["Auchindoun"] = {6, 1, "Auchindoun"}
c["Azjol-Nerub"] = {3, 1, "Azjol-Nerub"}
c["Baradin Hold"] = {4, 2, "Baradin Hold"}
c["Black Rook Hold"] = {7, 1, "Black Rook Hold"}
c["Black Temple"] = {2, 2, "Black Temple"}
c["Blackfathom Deeps"] = {1, 1, "Blackfathom Deeps"}
c["Blackrock Caverns"] = {4, 1, "Blackrock Caverns"}
c["Blackrock Depths"] = {1, 1, "Blackrock Depths"}
c["Blackrock Foundry"] = {6, 2, "Blackrock Foundry"}
c["Blackwing Descent"] = {4, 2, "Blackwing Descent"}
c["Blackwing Lair"] = {1, 2, "Blackwing Lair"}
c["Bloodmaul Slag Mines"] = {6, 1, "Bloodmaul Slag Mines"}
c["Broken Isles"] = {7, 2, "Broken Isles"}
c["Court of Stars"] = {7, 1, "Court of Stars"}
c["Darkheart Thicket"] = {7, 1, "Darkheart Thicket"}
c["Deadmines"] = {1, 1, "Deadmines"}
c["Dire Maul"] = {1, 1, "Dire Maul"}
c["Draenor"] = {6, 2, "Draenor"}
c["Dragon Soul"] = {4, 2, "Dragon Soul"}
c["Drak'Tharon Keep"] = {3, 1, "Drak'Tharon Keep"}
c["End Time"] = {4, 1, "End Time"}
c["Eye of Azshara"] = {7, 1, "Eye of Azshara"}
c["Firelands"] = {4, 2, "Firelands"}
c["Gate of the Setting Sun"] = {5, 1, "Gate of the Setting Sun"}
c["Gnomeregan"] = {1, 1, "Gnomeregan"}
c["Grim Batol"] = {4, 1, "Grim Batol"}
c["Grimrail Depot"] = {6, 1, "Grimrail Depot"}
c["Gruul's Lair"] = {2, 2, "Gruul's Lair"}
c["Gundrak"] = {3, 1, "Gundrak"}
c["Halls of Lightning"] = {3, 1, "Halls of Lightning"}
c["Halls of Origination"] = {4, 1, "Halls of Origination"}
c["Halls of Reflection"] = {3, 1, "Halls of Reflection"}
c["Halls of Stone"] = {3, 1, "Halls of Stone"}
c["Halls of Valor"] = {7, 1, "Halls of Valor"}
c["Heart of Fear"] = {5, 2, "Heart of Fear"}
c["Hellfire Citadel"] = {6, 2, "Hellfire Citadel"}
c["Hellfire Ramparts"] = {2, 1, "Hellfire Ramparts"}
c["Highmaul"] = {6, 2, "Highmaul"}
c["Hour of Twilight"] = {4, 1, "Hour of Twilight"}
c["Icecrown Citadel"] = {3, 2, "Icecrown Citadel"}
c["Iron Docks"] = {6, 1, "Iron Docks"}
c["Karazhan"] = {2, 2, "Karazhan"}
c["Lost City of the Tol'vir"] = {4, 1, "Lost City of the Tol'vir"}
c["Lower Blackrock Spire"] = {1, 1, "Lower Blackrock Spire"}
c["Magisters' Terrace"] = {2, 1, "Magisters' Terrace"}
c["Magtheridon's Lair"] = {2, 2, "Magtheridon's Lair"}
c["Mana-Tombs"] = {2, 1, "Mana-Tombs"}
c["Maraudon"] = {1, 1, "Maraudon"}
c["Maw of Souls"] = {7, 1, "Maw of Souls"}
c["Mogu'shan Palace"] = {5, 1, "Mogu'shan Palace"}
c["Mogu'shan Vaults"] = {5, 2, "Mogu'shan Vaults"}
c["Molten Core"] = {1, 2, "Molten Core"}
c["Naxxramas"] = {3, 2, "Naxxramas"}
c["Neltharion's Lair"] = {7, 1, "Neltharion's Lair"}
c["Old Hillsbrad Foothills"] = {2, 1, "Old Hillsbrad Foothills"}
c["Onyxia's Lair"] = {3, 2, "Onyxia's Lair"}
c["Pandaria"] = {5, 2, "Pandaria"}
c["Pit of Saron"] = {3, 1, "Pit of Saron"}
c["Ragefire Chasm"] = {1, 1, "Ragefire Chasm"}
c["Razorfen Downs"] = {1, 1, "Razorfen Downs"}
c["Razorfen Kraul"] = {1, 1, "Razorfen Kraul"}
c["Ruins of Ahn'Qiraj"] = {1, 2, "Ruins of Ahn'Qiraj"}
c["Scarlet Halls"] = {1, 1, "Scarlet Halls"}
c["Scarlet Monastery"] = {1, 1, "Scarlet Monastery"}
c["Scholomance"] = {1, 1, "Scholomance"}
c["Serpentshrine Cavern"] = {2, 2, "Serpentshrine Cavern"}
c["Sethekk Halls"] = {2, 1, "Sethekk Halls"}
c["Shado-Pan Monastery"] = {5, 1, "Shado-Pan Monastery"}
c["Shadow Labyrinth"] = {2, 1, "Shadow Labyrinth"}
c["Shadowfang Keep"] = {1, 1, "Shadowfang Keep"}
c["Shadowmoon Burial Grounds"] = {6, 1, "Shadowmoon Burial Grounds"}
c["Siege of Niuzao Temple"] = {5, 1, "Siege of Niuzao Temple"}
c["Siege of Orgrimmar"] = {5, 2, "Siege of Orgrimmar"}
c["Skyreach"] = {6, 1, "Skyreach"}
c["Stormstout Brewery"] = {5, 1, "Stormstout Brewery"}
c["Stratholme"] = {1, 1, "Stratholme"}
c["Sunwell Plateau"] = {2, 2, "Sunwell Plateau"}
c["Temple of Ahn'Qiraj"] = {1, 2, "Temple of Ahn'Qiraj"}
c["Temple of the Jade Serpent"] = {5, 1, "Temple of the Jade Serpent"}
c["Terrace of Endless Spring"] = {5, 2, "Terrace of Endless Spring"}
c["The Arcatraz"] = {2, 1, "The Arcatraz"}
c["The Arcway"] = {7, 1, "The Arcway"}
c["The Bastion of Twilight"] = {4, 2, "The Bastion of Twilight"}
c["The Battle for Mount Hyjal"] = {2, 2, "The Battle for Mount Hyjal"}
c["The Black Morass"] = {2, 1, "The Black Morass"}
c["The Blood Furnace"] = {2, 1, "The Blood Furnace"}
c["The Botanica"] = {2, 1, "The Botanica"}
c["The Culling of Stratholme"] = {3, 1, "The Culling of Stratholme"}
c["The Emerald Nightmare"] = {7, 2, "The Emerald Nightmare"}
c["The Everbloom"] = {6, 1, "The Everbloom"}
c["The Eye"] = {2, 2, "The Eye"}
c["The Eye of Eternity"] = {3, 2, "The Eye of Eternity"}
c["The Forge of Souls"] = {3, 1, "The Forge of Souls"}
c["The Mechanar"] = {2, 1, "The Mechanar"}
c["The Nexus"] = {3, 1, "The Nexus"}
c["The Nighthold"] = {7, 2, "The Nighthold"}
c["The Obsidian Sanctum"] = {3, 2, "The Obsidian Sanctum"}
c["The Oculus"] = {3, 1, "The Oculus"}
c["The Ruby Sanctum"] = {3, 2, "The Ruby Sanctum"}
c["The Shattered Halls"] = {2, 1, "The Shattered Halls"}
c["The Slave Pens"] = {2, 1, "The Slave Pens"}
c["The Steamvault"] = {2, 1, "The Steamvault"}
c["The Stockade"] = {1, 1, "The Stockade"}
c["The Stonecore"] = {4, 1, "The Stonecore"}
c["The Temple of Atal'hakkar"] = {1, 1, "The Temple of Atal'hakkar"}
c["The Underbog"] = {2, 1, "The Underbog"}
c["The Violet Hold"] = {3, 1, "The Violet Hold"}
c["The Vortex Pinnacle"] = {4, 1, "The Vortex Pinnacle"}
c["Throne of Thunder"] = {5, 2, "Throne of Thunder"}
c["Throne of the Four Winds"] = {4, 2, "Throne of the Four Winds"}
c["Throne of the Tides"] = {4, 1, "Throne of the Tides"}
c["Trial of the Champion"] = {3, 1, "Trial of the Champion"}
c["Trial of the Crusader"] = {3, 2, "Trial of the Crusader"}
c["Uldaman"] = {1, 1, "Uldaman"}
c["Ulduar"] = {3, 2, "Ulduar"}
c["Upper Blackrock Spire"] = {6, 1, "Upper Blackrock Spire"}
c["Utgarde Keep"] = {3, 1, "Utgarde Keep"}
c["Utgarde Pinnacle"] = {3, 1, "Utgarde Pinnacle"}
c["Vault of Archavon"] = {3, 2, "Vault of Archavon"}
c["Vault of the Wardens"] = {7, 1, "Vault of the Wardens"}
c["Wailing Caverns"] = {1, 1, "Wailing Caverns"}
c["Well of Eternity"] = {4, 1, "Well of Eternity"}
c["Zul'Aman"] = {4, 1, "Zul'Aman"}
c["Zul'Farrak"] = {1, 1, "Zul'Farrak"}
c["Zul'Gurub"] = {4, 1, "Zul'Gurub"}

c["Outland"] = {2, 2, "Outland"}

c["Trial of Valor"] = {7, 2, "Trial of Valor"}
c["Return to Karazhan"] = {7, 1, "Return to Karazhan"}
