if GetLocale() ~= "zhCN" then return end

local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'经典旧世', '燃烧的远征', '巫妖王之怒', '大地的裂变', '熊猫人之谜', '德拉诺之王', '军团再临'}
o.PARTY = {'Dungeon', 'Raid'}

c["安卡赫特：古代王国"] = {3, 1, "Ahn'kahet: The Old Kingdom"}
c["突袭紫罗兰监狱"] = {7, 1, "Assault on Violet Hold"}
c["奥金尼地穴"] = {2, 1, "Auchenai Crypts"}
c["奥金顿"] = {6, 1, "Auchindoun"}
c["艾卓-尼鲁布"] = {3, 1, "Azjol-Nerub"}
c["巴拉丁监狱"] = {4, 2, "Baradin Hold"}
c["黑鸦堡垒"] = {7, 1, "Black Rook Hold"}
c["黑暗神殿"] = {2, 2, "Black Temple"}
c["黑暗深渊"] = {1, 1, "Blackfathom Deeps"}
c["黑石岩窟"] = {4, 1, "Blackrock Caverns"}
c["黑石深渊"] = {1, 1, "Blackrock Depths"}
c["黑石铸造厂"] = {6, 2, "Blackrock Foundry"}
c["黑翼血环"] = {4, 2, "Blackwing Descent"}
c["黑翼之巢"] = {1, 2, "Blackwing Lair"}
c["血槌炉渣矿井"] = {6, 1, "Bloodmaul Slag Mines"}
c["破碎群岛"] = {7, 2, "Broken Isles"}
c["群星庭院"] = {7, 1, "Court of Stars"}
c["黑心林地"] = {7, 1, "Darkheart Thicket"}
c["死亡矿井"] = {1, 1, "Deadmines"}
c["厄运之槌"] = {1, 1, "Dire Maul"}
c["德拉诺"] = {6, 2, "Draenor"}
c["巨龙之魂"] = {4, 2, "Dragon Soul"}
c["达克萨隆要塞"] = {3, 1, "Drak'Tharon Keep"}
c["时光之末"] = {4, 1, "End Time"}
c["艾萨拉之眼"] = {7, 1, "Eye of Azshara"}
c["火焰之地"] = {4, 2, "Firelands"}
c["残阳关"] = {5, 1, "Gate of the Setting Sun"}
c["诺莫瑞根"] = {1, 1, "Gnomeregan"}
c["格瑞姆巴托"] = {4, 1, "Grim Batol"}
c["恐轨车站"] = {6, 1, "Grimrail Depot"}
c["格鲁尔的巢穴"] = {2, 2, "Gruul's Lair"}
c["古达克"] = {3, 1, "Gundrak"}
c["闪电大厅"] = {3, 1, "Halls of Lightning"}
c["起源大厅"] = {4, 1, "Halls of Origination"}
c["映像大厅"] = {3, 1, "Halls of Reflection"}
c["岩石大厅"] = {3, 1, "Halls of Stone"}
c["英灵殿"] = {7, 1, "Halls of Valor"}
c["恐惧之心"] = {5, 2, "Heart of Fear"}
c["地狱火堡垒"] = {6, 2, "Hellfire Citadel"}
c["地狱火城墙"] = {2, 1, "Hellfire Ramparts"}
c["悬槌堡"] = {6, 2, "Highmaul"}
c["暮光审判"] = {4, 1, "Hour of Twilight"}
c["冰冠堡垒"] = {3, 2, "Icecrown Citadel"}
c["钢铁码头"] = {6, 1, "Iron Docks"}
c["卡拉赞"] = {2, 2, "Karazhan"}
c["托维尔失落之城"] = {4, 1, "Lost City of the Tol'vir"}
c["黑石塔下层"] = {1, 1, "Lower Blackrock Spire"}
c["魔导师平台"] = {2, 1, "Magisters' Terrace"}
c["玛瑟里顿的巢穴"] = {2, 2, "Magtheridon's Lair"}
c["法力陵墓"] = {2, 1, "Mana-Tombs"}
c["玛拉顿"] = {1, 1, "Maraudon"}
c["噬魂之喉"] = {7, 1, "Maw of Souls"}
c["魔古山宫殿"] = {5, 1, "Mogu'shan Palace"}
c["魔古山宝库"] = {5, 2, "Mogu'shan Vaults"}
c["熔火之心"] = {1, 2, "Molten Core"}
c["纳克萨玛斯"] = {3, 2, "Naxxramas"}
c["奈萨里奥的巢穴"] = {7, 1, "Neltharion's Lair"}
c["旧希尔斯布莱德丘陵"] = {2, 1, "Old Hillsbrad Foothills"}
c["奥妮克希亚的巢穴"] = {3, 2, "Onyxia's Lair"}
c["潘达利亚"] = {5, 2, "Pandaria"}
c["萨隆矿坑"] = {3, 1, "Pit of Saron"}
c["怒焰裂谷"] = {1, 1, "Ragefire Chasm"}
c["剃刀高地"] = {1, 1, "Razorfen Downs"}
c["剃刀沼泽"] = {1, 1, "Razorfen Kraul"}
c["安其拉废墟"] = {1, 2, "Ruins of Ahn'Qiraj"}
c["血色大厅"] = {1, 1, "Scarlet Halls"}
c["血色修道院"] = {1, 1, "Scarlet Monastery"}
c["通灵学院"] = {1, 1, "Scholomance"}
c["毒蛇神殿"] = {2, 2, "Serpentshrine Cavern"}
c["塞泰克大厅"] = {2, 1, "Sethekk Halls"}
c["影踪禅院"] = {5, 1, "Shado-Pan Monastery"}
c["暗影迷宫"] = {2, 1, "Shadow Labyrinth"}
c["影牙城堡"] = {1, 1, "Shadowfang Keep"}
c["影月墓地"] = {6, 1, "Shadowmoon Burial Grounds"}
c["围攻砮皂寺"] = {5, 1, "Siege of Niuzao Temple"}
c["决战奥格瑞玛"] = {5, 2, "Siege of Orgrimmar"}
c["通天峰"] = {6, 1, "Skyreach"}
c["风暴烈酒酿造厂"] = {5, 1, "Stormstout Brewery"}
c["斯坦索姆"] = {1, 1, "Stratholme"}
c["太阳之井高地"] = {2, 2, "Sunwell Plateau"}
c["安其拉神殿"] = {1, 2, "Temple of Ahn'Qiraj"}
c["青龙寺"] = {5, 1, "Temple of the Jade Serpent"}
c["永春台"] = {5, 2, "Terrace of Endless Spring"}
c["禁魔监狱"] = {2, 1, "The Arcatraz"}
c["魔法回廊"] = {7, 1, "The Arcway"}
c["暮光堡垒"] = {4, 2, "The Bastion of Twilight"}
c["海加尔山之战"] = {2, 2, "The Battle for Mount Hyjal"}
c["黑色沼泽"] = {2, 1, "The Black Morass"}
c["鲜血熔炉"] = {2, 1, "The Blood Furnace"}
c["生态船"] = {2, 1, "The Botanica"}
c["净化斯坦索姆"] = {3, 1, "The Culling of Stratholme"}
c["翡翠梦魇"] = {7, 2, "The Emerald Nightmare"}
c["永茂林地"] = {6, 1, "The Everbloom"}
c["风暴要塞"] = {2, 2, "The Eye"}
c["永恒之眼"] = {3, 2, "The Eye of Eternity"}
c["灵魂洪炉"] = {3, 1, "The Forge of Souls"}
c["能源舰"] = {2, 1, "The Mechanar"}
c["魔枢"] = {3, 1, "The Nexus"}
c["暗夜要塞"] = {7, 2, "The Nighthold"}
c["黑曜石圣殿"] = {3, 2, "The Obsidian Sanctum"}
c["魔环"] = {3, 1, "The Oculus"}
c["红玉圣殿"] = {3, 2, "The Ruby Sanctum"}
c["破碎大厅"] = {2, 1, "The Shattered Halls"}
c["奴隶围栏"] = {2, 1, "The Slave Pens"}
c["蒸汽地窟"] = {2, 1, "The Steamvault"}
c["监狱"] = {1, 1, "The Stockade"}
c["巨石之核"] = {4, 1, "The Stonecore"}
c["阿塔哈卡神庙"] = {1, 1, "The Temple of Atal'hakkar"}
c["幽暗沼泽"] = {2, 1, "The Underbog"}
c["紫罗兰监狱"] = {3, 1, "The Violet Hold"}
c["旋云之巅"] = {4, 1, "The Vortex Pinnacle"}
c["雷电王座"] = {5, 2, "Throne of Thunder"}
c["风神王座"] = {4, 2, "Throne of the Four Winds"}
c["潮汐王座"] = {4, 1, "Throne of the Tides"}
c["冠军的试炼"] = {3, 1, "Trial of the Champion"}
c["十字军的试炼"] = {3, 2, "Trial of the Crusader"}
c["奥达曼"] = {1, 1, "Uldaman"}
c["奥杜尔"] = {3, 2, "Ulduar"}
c["黑石塔上层"] = {6, 1, "Upper Blackrock Spire"}
c["乌特加德城堡"] = {3, 1, "Utgarde Keep"}
c["乌特加德之巅"] = {3, 1, "Utgarde Pinnacle"}
c["阿尔卡冯的宝库"] = {3, 2, "Vault of Archavon"}
c["守望者地窟"] = {7, 1, "Vault of the Wardens"}
c["哀嚎洞穴"] = {1, 1, "Wailing Caverns"}
c["永恒之井"] = {4, 1, "Well of Eternity"}
c["祖阿曼"] = {4, 1, "Zul'Aman"}
c["祖尔法拉克"] = {1, 1, "Zul'Farrak"}
c["祖尔格拉布"] = {4, 1, "Zul'Gurub"}
