if GetLocale() ~= "deDE" then return end

local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn'kahet: Das Alte Königreich"] = {3, 1, "Ahn'kahet: The Old Kingdom"}
c["Sturm auf die Violette Festung"] = {7, 1, "Assault on Violet Hold"}
c["Auchenaikrypta"] = {2, 1, "Auchenai Crypts"}
c["Auchindoun"] = {6, 1, "Auchindoun"}
c["Azjol-Nerub"] = {3, 1, "Azjol-Nerub"}
c["Baradinfestung"] = {4, 2, "Baradin Hold"}
c["Die Rabenwehr"] = {7, 1, "Black Rook Hold"}
c["Der Schwarze Tempel"] = {2, 2, "Black Temple"}
c["Tiefschwarze Grotte"] = {1, 1, "Blackfathom Deeps"}
c["Schwarzfelshöhlen"] = {4, 1, "Blackrock Caverns"}
c["Schwarzfelstiefen"] = {1, 1, "Blackrock Depths"}
c["Schwarzfelsgießerei"] = {6, 2, "Blackrock Foundry"}
c["Pechschwingenabstieg"] = {4, 2, "Blackwing Descent"}
c["Pechschwingenhort"] = {1, 2, "Blackwing Lair"}
c["Blutschlägermine"] = {6, 1, "Bloodmaul Slag Mines"}
c["Die Verheerten Inseln"] = {7, 2, "Broken Isles"}
c["Der Hof der Sterne"] = {7, 1, "Court of Stars"}
c["Das Finsterherzdickicht"] = {7, 1, "Darkheart Thicket"}
c["Todesminen"] = {1, 1, "Deadmines"}
c["Düsterbruch"] = {1, 1, "Dire Maul"}
c["Draenor"] = {6, 2, "Draenor"}
c["Drachenseele"] = {4, 2, "Dragon Soul"}
c["Feste Drak'Tharon"] = {3, 1, "Drak'Tharon Keep"}
c["Endzeit"] = {4, 1, "End Time"}
c["Das Auge Azsharas"] = {7, 1, "Eye of Azshara"}
c["Feuerlande"] = {4, 2, "Firelands"}
c["Tor der Untergehenden Sonne"] = {5, 1, "Gate of the Setting Sun"}
c["Gnomeregan"] = {1, 1, "Gnomeregan"}
c["Grim Batol"] = {4, 1, "Grim Batol"}
c["Grimmgleisdepot"] = {6, 1, "Grimrail Depot"}
c["Gruuls Unterschlupf"] = {2, 2, "Gruul's Lair"}
c["Gundrak"] = {3, 1, "Gundrak"}
c["Hallen der Blitze"] = {3, 1, "Halls of Lightning"}
c["Hallen des Ursprungs"] = {4, 1, "Halls of Origination"}
c["Hallen der Reflexion"] = {3, 1, "Halls of Reflection"}
c["Hallen des Steins"] = {3, 1, "Halls of Stone"}
c["Die Hallen der Tapferkeit"] = {7, 1, "Halls of Valor"}
c["Das Herz der Angst"] = {5, 2, "Heart of Fear"}
c["Höllenfeuerzitadelle"] = {6, 2, "Hellfire Citadel"}
c["Höllenfeuerbollwerk"] = {2, 1, "Hellfire Ramparts"}
c["Hochfels"] = {6, 2, "Highmaul"}
c["Die Stunde des Zwielichts"] = {4, 1, "Hour of Twilight"}
c["Die Eiskronenzitadelle"] = {3, 2, "Icecrown Citadel"}
c["Eisendocks"] = {6, 1, "Iron Docks"}
c["Karazhan"] = {2, 2, "Karazhan"}
c["Die Verlorene Stadt der Tol'vir"] = {4, 1, "Lost City of the Tol'vir"}
c["Untere Schwarzfelsspitze"] = {1, 1, "Lower Blackrock Spire"}
c["Terrasse der Magister"] = {2, 1, "Magisters' Terrace"}
c["Magtheridons Kammer"] = {2, 2, "Magtheridon's Lair"}
c["Managruft"] = {2, 1, "Mana-Tombs"}
c["Maraudon"] = {1, 1, "Maraudon"}
c["Der Seelenschlund"] = {7, 1, "Maw of Souls"}
c["Mogu'shanpalast"] = {5, 1, "Mogu'shan Palace"}
c["Mogu'shangewölbe"] = {5, 2, "Mogu'shan Vaults"}
c["Der Geschmolzene Kern"] = {1, 2, "Molten Core"}
c["Naxxramas"] = {3, 2, "Naxxramas"}
c["Neltharions Hort"] = {7, 1, "Neltharion's Lair"}
c["Vorgebirge des Alten Hügellands"] = {2, 1, "Old Hillsbrad Foothills"}
c["Onyxias Hort"] = {3, 2, "Onyxia's Lair"}
c["Pandaria"] = {5, 2, "Pandaria"}
c["Grube von Saron"] = {3, 1, "Pit of Saron"}
c["Der Flammenschlund"] = {1, 1, "Ragefire Chasm"}
c["Hügel der Klingenhauer"] = {1, 1, "Razorfen Downs"}
c["Kral der Klingenhauer"] = {1, 1, "Razorfen Kraul"}
c["Ruinen von Ahn'Qiraj"] = {1, 2, "Ruins of Ahn'Qiraj"}
c["Scharlachrote Hallen"] = {1, 1, "Scarlet Halls"}
c["Das Scharlachrote Kloster"] = {1, 1, "Scarlet Monastery"}
c["Scholomance"] = {1, 1, "Scholomance"}
c["Höhle des Schlangenschreins"] = {2, 2, "Serpentshrine Cavern"}
c["Sethekkhallen"] = {2, 1, "Sethekk Halls"}
c["Das Shado-Pan-Kloster"] = {5, 1, "Shado-Pan Monastery"}
c["Schattenlabyrinth"] = {2, 1, "Shadow Labyrinth"}
c["Burg Schattenfang"] = {1, 1, "Shadowfang Keep"}
c["Schattenmondgrabstätte"] = {6, 1, "Shadowmoon Burial Grounds"}
c["Belagerung des Niuzaotempels"] = {5, 1, "Siege of Niuzao Temple"}
c["Die Schlacht um Orgrimmar"] = {5, 2, "Siege of Orgrimmar"}
c["Himmelsnadel"] = {6, 1, "Skyreach"}
c["Die Brauerei Sturmbräu"] = {5, 1, "Stormstout Brewery"}
c["Stratholme"] = {1, 1, "Stratholme"}
c["Sonnenbrunnenplateau"] = {2, 2, "Sunwell Plateau"}
c["Tempel von Ahn'Qiraj"] = {1, 2, "Temple of Ahn'Qiraj"}
c["Tempel der Jadeschlange"] = {5, 1, "Temple of the Jade Serpent"}
c["Terrasse d. Endlosen Frühlings"] = {5, 2, "Terrace of Endless Spring"}
c["Die Arkatraz"] = {2, 1, "The Arcatraz"}
c["Der Arkus"] = {7, 1, "The Arcway"}
c["Die Bastion des Zwielichts"] = {4, 2, "The Bastion of Twilight"}
c["Die Schlacht um den Hyjal"] = {2, 2, "The Battle for Mount Hyjal"}
c["Der Schwarze Morast"] = {2, 1, "The Black Morass"}
c["Der Blutkessel"] = {2, 1, "The Blood Furnace"}
c["Die Botanika"] = {2, 1, "The Botanica"}
c["Das Ausmerzen von Stratholme"] = {3, 1, "The Culling of Stratholme"}
c["Der Smaragdgrüne Alptraum"] = {7, 2, "The Emerald Nightmare"}
c["Der Immergrüne Flor"] = {6, 1, "The Everbloom"}
c["Das Auge"] = {2, 2, "The Eye"}
c["Das Auge der Ewigkeit"] = {3, 2, "The Eye of Eternity"}
c["Die Seelenschmiede"] = {3, 1, "The Forge of Souls"}
c["Die Mechanar"] = {2, 1, "The Mechanar"}
c["Der Nexus"] = {3, 1, "The Nexus"}
c["Die Nachtfestung"] = {7, 2, "The Nighthold"}
c["Das Obsidiansanktum"] = {3, 2, "The Obsidian Sanctum"}
c["Das Oculus"] = {3, 1, "The Oculus"}
c["Das Rubinsanktum"] = {3, 2, "The Ruby Sanctum"}
c["Die Zerschmetterten Hallen"] = {2, 1, "The Shattered Halls"}
c["Die Sklavenunterkünfte"] = {2, 1, "The Slave Pens"}
c["Die Dampfkammer"] = {2, 1, "The Steamvault"}
c["Das Verlies"] = {1, 1, "The Stockade"}
c["Der Steinerne Kern"] = {4, 1, "The Stonecore"}
c["Der Tempel von Atal'Hakkar"] = {1, 1, "The Temple of Atal'hakkar"}
c["Der Tiefensumpf"] = {2, 1, "The Underbog"}
c["Die Violette Festung"] = {3, 1, "The Violet Hold"}
c["Der Vortexgipfel"] = {4, 1, "The Vortex Pinnacle"}
c["Thron des Donners"] = {5, 2, "Throne of Thunder"}
c["Thron der Vier Winde"] = {4, 2, "Throne of the Four Winds"}
c["Thron der Gezeiten"] = {4, 1, "Throne of the Tides"}
c["Prüfung des Champions"] = {3, 1, "Trial of the Champion"}
c["Prüfung des Kreuzfahrers"] = {3, 2, "Trial of the Crusader"}
c["Uldaman"] = {1, 1, "Uldaman"}
c["Ulduar"] = {3, 2, "Ulduar"}
c["Obere Schwarzfelsspitze"] = {6, 1, "Upper Blackrock Spire"}
c["Burg Utgarde"] = {3, 1, "Utgarde Keep"}
c["Turm Utgarde"] = {3, 1, "Utgarde Pinnacle"}
c["Archavons Kammer"] = {3, 2, "Vault of Archavon"}
c["Das Verlies der Wächterinnen"] = {7, 1, "Vault of the Wardens"}
c["Höhlen des Wehklagens"] = {1, 1, "Wailing Caverns"}
c["Brunnen der Ewigkeit"] = {4, 1, "Well of Eternity"}
c["Zul'Aman"] = {4, 1, "Zul'Aman"}
c["Zul'Farrak"] = {1, 1, "Zul'Farrak"}
c["Zul'Gurub"] = {4, 1, "Zul'Gurub"}
