if GetLocale() ~= "frFR" then return end

local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn’kahet : l’Ancien royaume"] = {3, 1, "Ahn'kahet: The Old Kingdom"}
c["Assaut sur le fort Pourpre"] = {7, 1, "Assault on Violet Hold"}
c["Cryptes Auchenaï"] = {2, 1, "Auchenai Crypts"}
c["Auchindoun"] = {6, 1, "Auchindoun"}
c["Azjol-Nérub"] = {3, 1, "Azjol-Nerub"}
c["Bastion de Baradin"] = {4, 2, "Baradin Hold"}
c["Bastion du Freux"] = {7, 1, "Black Rook Hold"}
c["Le Temple noir"] = {2, 2, "Black Temple"}
c["Profondeurs de Brassenoire"] = {1, 1, "Blackfathom Deeps"}
c["Cavernes de Rochenoire"] = {4, 1, "Blackrock Caverns"}
c["Profondeurs de Rochenoire"] = {1, 1, "Blackrock Depths"}
c["Fonderie des Rochenoires"] = {6, 2, "Blackrock Foundry"}
c["Descente de l’Aile noire"] = {4, 2, "Blackwing Descent"}
c["Repaire de l’Aile noire"] = {1, 2, "Blackwing Lair"}
c["Mine de la Masse-Sanglante"] = {6, 1, "Bloodmaul Slag Mines"}
c["Îles Brisées"] = {7, 2, "Broken Isles"}
c["Cour des Étoiles"] = {7, 1, "Court of Stars"}
c["Fourré Sombrecœur"] = {7, 1, "Darkheart Thicket"}
c["Les Mortemines"] = {1, 1, "Deadmines"}
c["Hache-Tripes"] = {1, 1, "Dire Maul"}
c["Draenor"] = {6, 2, "Draenor"}
c["L’Âme des dragons"] = {4, 2, "Dragon Soul"}
c["Donjon de Drak’Tharon"] = {3, 1, "Drak'Tharon Keep"}
c["La Fin des temps"] = {4, 1, "End Time"}
c["L’Œil d’Azshara"] = {7, 1, "Eye of Azshara"}
c["Terres de Feu"] = {4, 2, "Firelands"}
c["Porte du Soleil couchant"] = {5, 1, "Gate of the Setting Sun"}
c["Gnomeregan"] = {1, 1, "Gnomeregan"}
c["Grim Batol"] = {4, 1, "Grim Batol"}
c["Dépôt de Tristerail"] = {6, 1, "Grimrail Depot"}
c["Repaire de Gruul"] = {2, 2, "Gruul's Lair"}
c["Gundrak"] = {3, 1, "Gundrak"}
c["Les salles de Foudre"] = {3, 1, "Halls of Lightning"}
c["Salles de l’Origine"] = {4, 1, "Halls of Origination"}
c["Salles des Reflets"] = {3, 1, "Halls of Reflection"}
c["Les salles de Pierre"] = {3, 1, "Halls of Stone"}
c["Salles des Valeureux"] = {7, 1, "Halls of Valor"}
c["Cœur de la peur"] = {5, 2, "Heart of Fear"}
c["Citadelle des Flammes infernales"] = {6, 2, "Hellfire Citadel"}
c["Remparts des Flammes infernales"] = {2, 1, "Hellfire Ramparts"}
c["Cognefort"] = {6, 2, "Highmaul"}
c["L’Heure du Crépuscule"] = {4, 1, "Hour of Twilight"}
c["Citadelle de la Couronne de glace"] = {3, 2, "Icecrown Citadel"}
c["Quais de Fer"] = {6, 1, "Iron Docks"}
c["Karazhan"] = {2, 2, "Karazhan"}
c["Cité perdue des Tol’vir"] = {4, 1, "Lost City of the Tol'vir"}
c["Bas du pic Rochenoire"] = {1, 1, "Lower Blackrock Spire"}
c["Terrasse des Magistères"] = {2, 1, "Magisters' Terrace"}
c["Le repaire de Magtheridon"] = {2, 2, "Magtheridon's Lair"}
c["Tombes-mana"] = {2, 1, "Mana-Tombs"}
c["Maraudon"] = {1, 1, "Maraudon"}
c["La Gueule des âmes"] = {7, 1, "Maw of Souls"}
c["Palais Mogu’shan"] = {5, 1, "Mogu'shan Palace"}
c["Caveaux Mogu’shan"] = {5, 2, "Mogu'shan Vaults"}
c["Cœur du Magma"] = {1, 2, "Molten Core"}
c["Naxxramas"] = {3, 2, "Naxxramas"}
c["Repaire de Neltharion"] = {7, 1, "Neltharion's Lair"}
c["Contreforts de Hautebrande d’antan"] = {2, 1, "Old Hillsbrad Foothills"}
c["Repaire d’Onyxia"] = {3, 2, "Onyxia's Lair"}
c["Pandarie"] = {5, 2, "Pandaria"}
c["Fosse de Saron"] = {3, 1, "Pit of Saron"}
c["Gouffre de Ragefeu"] = {1, 1, "Ragefire Chasm"}
c["Souilles de Tranchebauge"] = {1, 1, "Razorfen Downs"}
c["Kraal de Tranchebauge"] = {1, 1, "Razorfen Kraul"}
c["Ruines d’Ahn’Qiraj"] = {1, 2, "Ruins of Ahn'Qiraj"}
c["Salles Écarlates"] = {1, 1, "Scarlet Halls"}
c["Monastère Écarlate"] = {1, 1, "Scarlet Monastery"}
c["Scholomance"] = {1, 1, "Scholomance"}
c["Caverne du sanctuaire du Serpent"] = {2, 2, "Serpentshrine Cavern"}
c["Les salles des Sethekk"] = {2, 1, "Sethekk Halls"}
c["Monastère des Pandashan"] = {5, 1, "Shado-Pan Monastery"}
c["Labyrinthe des Ombres"] = {2, 1, "Shadow Labyrinth"}
c["Donjon d’Ombrecroc"] = {1, 1, "Shadowfang Keep"}
c["Terres sacrées d’Ombrelune"] = {6, 1, "Shadowmoon Burial Grounds"}
c["Siège du temple de Niuzao"] = {5, 1, "Siege of Niuzao Temple"}
c["Siège d’Orgrimmar"] = {5, 2, "Siege of Orgrimmar"}
c["Orée-du-Ciel"] = {6, 1, "Skyreach"}
c["Brasserie Brune d’Orage"] = {5, 1, "Stormstout Brewery"}
c["Stratholme"] = {1, 1, "Stratholme"}
c["Plateau du Puits de soleil"] = {2, 2, "Sunwell Plateau"}
c["Temple d’Ahn’Qiraj"] = {1, 2, "Temple of Ahn'Qiraj"}
c["Temple du Serpent de jade"] = {5, 1, "Temple of the Jade Serpent"}
c["Terrasse Printanière"] = {5, 2, "Terrace of Endless Spring"}
c["L’Arcatraz"] = {2, 1, "The Arcatraz"}
c["L’Arcavia"] = {7, 1, "The Arcway"}
c["Le bastion du Crépuscule"] = {4, 2, "The Bastion of Twilight"}
c["La bataille du mont Hyjal"] = {2, 2, "The Battle for Mount Hyjal"}
c["Le Noir marécage"] = {2, 1, "The Black Morass"}
c["La Fournaise du sang"] = {2, 1, "The Blood Furnace"}
c["La Botanica"] = {2, 1, "The Botanica"}
c["L’Épuration de Stratholme"] = {3, 1, "The Culling of Stratholme"}
c["Le Cauchemar d’émeraude"] = {7, 2, "The Emerald Nightmare"}
c["La Flore éternelle"] = {6, 1, "The Everbloom"}
c["L’Œil"] = {2, 2, "The Eye"}
c["L’Œil de l’éternité"] = {3, 2, "The Eye of Eternity"}
c["La Forge des Âmes"] = {3, 1, "The Forge of Souls"}
c["Le Méchanar"] = {2, 1, "The Mechanar"}
c["Le Nexus"] = {3, 1, "The Nexus"}
c["Palais Sacrenuit"] = {7, 2, "The Nighthold"}
c["Le sanctum Obsidien"] = {3, 2, "The Obsidian Sanctum"}
c["L’Oculus"] = {3, 1, "The Oculus"}
c["Le sanctum Rubis"] = {3, 2, "The Ruby Sanctum"}
c["Les salles Brisées"] = {2, 1, "The Shattered Halls"}
c["Les enclos aux esclaves"] = {2, 1, "The Slave Pens"}
c["Le caveau de la Vapeur"] = {2, 1, "The Steamvault"}
c["La Prison"] = {1, 1, "The Stockade"}
c["Le Cœur-de-Pierre"] = {4, 1, "The Stonecore"}
c["Le temple d’Atal’Hakkar"] = {1, 1, "The Temple of Atal'hakkar"}
c["La Basse-tourbière"] = {2, 1, "The Underbog"}
c["Le fort Pourpre"] = {3, 1, "The Violet Hold"}
c["La cime du Vortex"] = {4, 1, "The Vortex Pinnacle"}
c["Trône du tonnerre"] = {5, 2, "Throne of Thunder"}
c["Trône des quatre vents"] = {4, 2, "Throne of the Four Winds"}
c["Trône des marées"] = {4, 1, "Throne of the Tides"}
c["L’épreuve du champion"] = {3, 1, "Trial of the Champion"}
c["L’épreuve du croisé"] = {3, 2, "Trial of the Crusader"}
c["Uldaman"] = {1, 1, "Uldaman"}
c["Ulduar"] = {3, 2, "Ulduar"}
c["Sommet du pic Rochenoire"] = {6, 1, "Upper Blackrock Spire"}
c["Cime d’Utgarde"] = {3, 1, "Utgarde Keep"}
c["Donjon d’Utgarde"] = {3, 1, "Utgarde Pinnacle"}
c["Caveau d’Archavon"] = {3, 2, "Vault of Archavon"}
c["Caveau des Gardiennes"] = {7, 1, "Vault of the Wardens"}
c["Cavernes des Lamentations"] = {1, 1, "Wailing Caverns"}
c["Puits d’éternité"] = {4, 1, "Well of Eternity"}
c["Zul’Aman"] = {4, 1, "Zul'Aman"}
c["Zul’Farrak"] = {1, 1, "Zul'Farrak"}
c["Zul’Gurub"] = {4, 1, "Zul'Gurub"}
