if GetLocale() ~= "zhTW" then return end

local o = mOnWardrobe
if o.strings == nil then o.strings = {} end
local s = o.strings

s["Page N"] = "第 %i 頁"
s["Refresh Instance"] = "重新整理副本"
s["Refresh Items"] = "重新整理物品"
s["Current Instance"] = "當前副本"
s["Click Refresh Info"] = "點擊上方的 %s 按鈕載入副本"
s["Progress"] = "進度"
s["Missing Items"] = "尚未收集的物品"
s["Instance"] = "副本"
s["Hide List Option"] = "開啟副本時隱藏清單"
s["Refresh Confirmation"] = "這個動作將會使遊戲停頓幾秒，\n是否要繼續?"
s["Yes"] = "是"
s["No"] = "否"
s["Open Options"] = "開啟設定選項"
s["Options"] = "選項"
s["Close"] = "關閉"
s["Defaults"] = "預設值"
s["General"] = "一般"
s["Debug"] = "除錯"
s["Debug Info"] = "這裡的每一個選項都是實驗性質，有可能會造成遊戲無法繼續運行。別說我沒警告過你。"
s["Disable Progress"] = "停用進度"
s["Disable Progress Info"] = "應該會加快重新整理所有物品的速度。"

s["Refreshing"] = "正在重新整理"
s["Hide Minimap"] = "隱藏小地圖按鈕"

s["Disable Confirmation"] = "停用重新整理確認"
s["You're beautiful"] = "你今天看起來真美"
s["Happy Sunday"] = "週日愉快!"
s["Other Sources"] = "其他來源"
s["Sources"] = "來源"

s["Completionist Mode"] = "休閒模式"
s["Completionist Mode Info"] = "只有在收集到特定的物品後，才會列出相關物品。"

s["Open MiniList"] = "開啟迷你清單"

-- Missing localization
s["Wardrobe Helper"] = "衣櫃永遠少一件"
s["Special"] = "特殊"
s["Custom Categories"] = "自訂分類"
s["Unknown"] = "未知"
s["Boss drop"] = "首領掉落"
s["Quests"] = "任務"
s["Vendor"] = "商人"
s["World/Instance Drop"] = "世界/副本掉落"
s["Achievements"] = "成就"
s["Professions"] = "專業"
s["Other"] = "其他"
s["Normal"] = "普通"
s["25 Player"] = "25人"
s["25 Player (Heroic)"] = "25人(英雄難度)"
s["Heroic"] = "英雄"
s["Looking For Raid"] = "尋求團隊"
s["Mythic"] = "傳奇"
s["Tier 1"] = "T1 套裝"
s["Tier 2"] = "T2 套裝"
s["Tier 3"] = "T3 套裝"
s["Tier 4"] = "T4 套裝"
s["Tier 5"] = "T5 套裝"
s["Tier 6"] = "T6 套裝"
s["Tier 7"] = "T7 套裝"
s["Tier 8"] = "T8 套裝"
s["Tier 9"] = "T9 套裝"
s["Tier 10"] = "T10 套裝"
s["Tier 11"] = "T11 套裝"
s["Tier 12"] = "T12 套裝"
s["Tier 13"] = "T13 套裝"
s["Tier 14"] = "T14 套裝"
s["Tier 15"] = "T15 套裝"
s["Tier 16"] = "T16 套裝"
s["Tier 17"] = "T17 套裝"
s["Tier 18"] = "T18 套裝"
s["Tier 19"] = "T19 套裝"

s["mOnAr's Addons"] = "收藏-衣櫃"
s["mOnAr's Addons Options"] = "mOnAr 的插件選項"
s["This category contains Settings for every addon made by mOnAr (Seamoon)"] = "這裡包含了 mOnAr (Seamoon) 製作的所有插件的設定"
